name: http_service
description: A service for managing http requests.
version: 1.0.6

environment:
  sdk: ">=3.5.1 < 4.0.0"

dev_dependencies:
  lints: ^5.0.0
  test: ^1.16.0
dependencies:
  http: ^1.1.0
