name: http_service
description: A service for managing http requests.
version: 1.0.3

environment:
  sdk: '>=2.19.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  http: ^1.1.0
